---
# tasks file for java alternatives

- name: set alternatives link for java
  alternatives:
    name: 'java'
    link: '/usr/bin/java'
    path: "{{ java_home }}/bin/java"
    priority: 1000
  when: java_set_default
  tags:
    - java
    - bootstrap

- name: set alternatives link for javac
  alternatives:
    name: 'javac'
    link: '/usr/bin/javac'
    path: "{{ java_home }}/bin/javac"
    priority: 1000
  when: java_set_default
  tags:
    - java
    - bootstrap

- name: set alternatives link for jar
  alternatives:
    name: 'jar'
    link: '/usr/bin/jar'
    path: "{{ java_home }}/bin/jar"
    priority: 1000
  when: java_set_default
  tags:
    - java
    - bootstrap
